# Generated by Django 4.2.2 on 2023-06-28 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lunch_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="voters",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
